@server = http://localhost:4004
@me = Authorization: Basic {{$processEnv USER}}:
@basic = Authorization: Basic admin:admin
### ------------------------------------------------------------------------
# Get Weight
GET  {{server}}/v2/catalog/ProdutosCrud 
content-type: application/json
{{me}}

### Function get product matrix
GET {{server}}/v2/catalog/getMatrix?ID='46f5dd03-1925-4a5f-84f8-520c7f25e255'
Accept: application/json
Content-Type: application/json
{{basic}}

